### PR TITLE
Added header and footer tabs to Inventory-Scan. 

### PR DESCRIPTION
**Pull request by TomMakkink**
Howsit! 

What would you like as the content for the scan tab? Is this to scan an item? Like taking a picture? 

Regards, 
Tom

### CODE REVIEW

**Comment by TomMakkink** [comment]
Sorry I didn't see that you had updated the Inventory Scan issue! Will do the content now and resubmit.

**Comment by scheepers** [comment]
:)

Thanks you!

**Comment by scheepers** [comment]
Hi Tom!

Wow, I think I've been inviting the wrong person to our team.

You're not TomasMakkink, are you?

Please could you do a pull on your side from the master branch, I've made some updates/renames that may cause some conflicts...? I also added the layout guide, if people want to design some skins (please don't take it as comment on your wireframes - I'm awkward like that - sorry that I blundered there)

Thanks for you patience and time on this!

**Comment by TomMakkink** [comment]
Hi Scheepers, 

Yes sorry for the confusion! Turns out I had another account set up that I was unaware of, on an email address I used to use (must have set it up in first year or something and forgot about it, lol). Anyway! I've deleted that. 

This account, TomMakkink, is the one I am actually using! Again my apologies for the confusion. 

Okay perfect, I will do the pull request before I do any more work on the project. My apologies for being fairly quiet over the last two weeks or so. I am in the thick of exams, but should be more active again from next week. 

Please don't stress about the comments! Just happy to be helping!

**Comment by scheepers** [comment]
lol. It's all good, good luck with your exams!

**Pull request closed without merging**
